# Site settings
title: Bark
email: Kev.Kirsche@gmail.com
description: Scare The Details Out Of Monit
baseurl: "/Bark" # the subpath of your site, e.g. /blog/
url: "http://kkirsche.github.io" # the base hostname & protocol for your site
twitter_username: kkirsche
github_username:  kkirsche

# Build settings
markdown: github-markdown
